name:                rhc
version:             0.1.0.0
github:              "dponya/rhc"
license:             MIT
author:              "Yerbol Altynbek"
maintainer:          "Yerbol Altynbek"
copyright:           "2022 Yerbol Altynbek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            JSON-RPC library
# category:            Network, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rhc#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- http-types
- bytestring
- aeson

library:
  source-dirs: src
executables:
  simple-server:
    main: examples/simple-server.hs
    dependencies:
      - rhc
      - aeson

tests:
  rhc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rhc
