name:                rhc
version:             0.1.0.0
github:              "dponya/rhc"
license:             MIT
author:              "Yerbol Altynbek"
maintainer:          "Yerbol Altynbek"
copyright:           "2022 Yerbol Altynbek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            JSON-RPC library
# category:            Network, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rhc#readme>

dependencies:
- base >= 4.7 && < 5
- aeson      >= 2.0.3.0 && < 2.0.4.0
- bytestring >= 0.10.12 && < 0.11
- vector     >= 0.12.3.1 && < 0.13
- http-types >= 0.12.3 && < 0.13
- wai        >= 3.2.3 && < 3.3
- warp       >= 3.3.20 && < 3.4

library:
  source-dirs: src
executables:
  simple-server:
    main: examples/simple-server.hs
    dependencies:
      - rhc
      - aeson
      - vector
tests:
  rhc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rhc
